import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'

import { Inter } from 'next/font/google'
import { cookieToInitialState } from 'wagmi'
import { config } from '@/config'
import { Web3Modal } from "@/context/Web3Modal";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Flower Girls Seed Purse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={inter.className}>
      <Web3Modal initialState={initialState}>{children}</Web3Modal>
      </body>
    </html>
  )
}
